### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by phillpafford** [sagark/thinkdisp#10]
executing the command: thinkdisp

I get this error:

<code>
Traceback (most recent call last):
  File "/usr/local/bin/thinkdisp", line 285, in <module>
    subprocess.call(["killdisp"])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
</code>

in the code thinkdisp I added this option to line 285:

original:
subprocess.call(["killdisp"])

modified:
subprocess.call(["killdisp"], shell=True)

Now when I execute the command: thinkdisp

I get this error

<code>
/usr/bin/killdisp: 1: /usr/bin/killdisp: Syntax error: "(" unexpected
"1280x1024_59.90"  108.70  1280 1360 1496 1712  1024 1025 1028 1060  -HSync +Vsync
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  150 (RANDR)
  Minor opcode of failed request:  16 (RRCreateMode)
  Serial number of failed request:  30
  Current serial number in output stream:  30
"1024x768_59.90"  64.00  1024 1080 1184 1344  768 769 772 795  -HSync +Vsync
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  150 (RANDR)
  Minor opcode of failed request:  16 (RRCreateMode)
  Serial number of failed request:  30
  Current serial number in output stream:  30
</code>

**Comment by sagark** [comment]
Everything from the 2nd line on is normal - it just means that those resolutions have been added to xrandr already and it likes to complain when that happens (but no harm done). The first looks like a problem though, I'll look into it.

**Comment by sagark** [comment]
Ok, I've attempted a fix. I can't replicate the error on my machine so can you try this out?

Download/extract the latest zip for this branch: https://github.com/sagark/thinkdisp/tree/killdisp_fix
<code>$ cd EXTRACTED_FOLDER
$ make
$ sudo python setup.py install
$ thinkdisp
</code>

**Comment by phillpafford** [comment]
I reinstalled using 12.04 64bit, was running the 32bit and I think this was the problem
