### ISSUE TITLE
First run check crashes with old configuration

### ISSUE THREAD

**Issue by jethrogb** [sagark/thinkdisp#6]
The latest update adds the configuration section [First run]. If you don't add this section manually, thinkdisp crashes when run on line 278 (if tmpUconf.perm_fixed not in "True"), because perm_fixed does not exist. I don't know python, but it sounds like a trivial fix to check if tmpUconf.perm_fixed exists before accessing it.

**Comment by sagark** [comment]
Thanks for the heads up, this should be fixed as of cec8d2183637e15313253a52648515d449bedff1.
