### ISSUE TITLE
Read monitor's EDID to add possible modes to VIRTUAL output and Thinkdisp

### ISSUE THREAD

**Issue by jethrogb** [sagark/thinkdisp#7]
The nvidia-settings utility is actually open-source [1]. It should be possible to use that to read monitor information (EDID, see [2]) when you attach monitors and automatically add modelines to the VIRTUAL output as well as Thinkdisp.

[1] ftp://download.nvidia.com/XFree86/nvidia-settings/
[2] http://polypux.org/projects/read-edid/

**Comment by jethrogb** [comment]
This was meant as a feature request, but I can't seem to add labels.

**Comment by sagark** [comment]
I'll check that out, looks good. read-edid doesn't look like it's working in it's current form for us, looks like it'll need some tweaking.
